### ISSUE TITLE
Ze Leaves are Fighting!

### ISSUE THREAD

**Issue by ZenithAstralis** [TeamMidnightDust/BetterLeavesPack#11]
I'm getting lots of z-fighting where the leaves stick out of the corners of the leaf blocks and overlap with those from diagonally adjacent blocks. [These screenshots](https://drive.google.com/drive/folders/1Qfaz4OucxcnYGTsgD2oU5YDJtnFWUgr-?usp=sharing) are from Traverse's Autumnal Woods biome, but I got the same thing from the vanilla Forest biome with Oak leaves.

**Comment by Motschen** [comment]
Are you using the forge or the fabric version of Traverse?

**Comment by ZenithAstralis** [comment]
If I am remembering correctly it was fabric. The idea had been to get
better performance on slower computers.

**Comment by Motschen** [comment]
Should be fixed by now.
