### ISSUE TITLE
Make working on MC 1.17.x

### ISSUE THREAD

**Issue by lospejos** [TeamMidnightDust/BetterLeavesPack#14]
Hi!
When trying this mod on MC 1.17 (with OptiFine and Fabric), I got error saying this mod is incompatible because it's made for older 
version. Could you please upgrade this mod to make it working with MC 1.17.x?

Thanks.

**Comment by Motschen** [comment]
You can just ignore that warning, the pack is not affected. 
In the next release, I'll update the pack format so the warning doesn't show up anymore.
