### ISSUE TITLE
Filename Compatibility with MultiMC

### ISSUE THREAD

**Issue by murdick** [TeamMidnightDust/BetterLeavesPack#18]
It seems that multimc has difficulty extracting filenames with special characters in them. Specifically it seems to choke with the § section symbol.

   24.162 W Failed to extract file "resourcepacks/Better-Leaves-6.0-1.13+\u00156.zip" to "resourcepacks/Better-Leaves-6.0-1.13+\u00156.zip"

this is reported a couple times on their discord server and also in an open issue on github https://github.com/MultiMC/Launcher/issues/4182

**Comment by Motschen** [comment]
Fixed.
