### ISSUE TITLE
Small incompatibility with Better Vanilla Building texture pack - dark forest biome

### ISSUE THREAD

**Issue by spiritedsnowcat** [TeamMidnightDust/BetterLeavesPack#19]
**Versions**

Minecraft 1.18.1 (forge-39.0.5)
Better Vanilla Building 2.66.1
Motschen's Better Leaves 6.1-1.13+
Terralith 2.0 Overworld Evolved 2.0.5
Optifine 1.18.1 HD U H4

**Summary**

It looks like dark forests have the wrong leaf colors with Better Vanilla Building and Optifine. Disabling the texture pack seems to fix the problem. Not sure if that's a problem with the texture pack or the better leaves resource pack.

**Screenshot**

![2021-12-20_11 42 39](https://user-images.githubusercontent.com/12414663/146826164-92da8966-12d3-4dfc-a466-5c6e25471a57.png)

**Comment by Motschen** [comment]
I've seen this kind of issue before and it's probably caused by OptiFine's terrible implementation of custom colors, so there's nothing I can do about it.
