### ISSUE TITLE
Flowering Azalea Leaves error texture version 1.19.2

### ISSUE THREAD

**Issue by DexxKnight1** [TeamMidnightDust/BetterLeavesPack#35]
Flowering Azalea Leaves placed down shows texture error. In my inventory and i JEI looks just fine, as you can see in the picture below.

![Screenshot 2023-09-28 120138](https://github.com/TeamMidnightDust/BetterLeavesPack/assets/78975662/097be683-70fd-477c-9fd3-c573e45bd310)

**Comment by ForsakenHarmony** [comment]
Having the same issue for ` Oh The Biomes You'll Go` leaves on 1.18.2

**Comment by Motschen** [comment]
Likely caused by a mod or another resourcepack changing something very weird about the texture.
For the BYG issue, 1.18.2 is not supported anymore.
