### ISSUE TITLE
Support for Leaves from Bountiful Fares Mod (1.20.1)

### ISSUE THREAD

**Issue by ghost** [TeamMidnightDust/BetterLeavesPack#43]
Great mod that recently came out :)

https://modrinth.com/mod/bountiful-fares

![image](https://github.com/TeamMidnightDust/BetterLeavesPack/assets/73998874/11d75fd0-3967-48ac-8766-0a3ab3976009)

**Comment by Liamgrayskull** [comment]
This test pack in the PR can be used for support https://github.com/TeamMidnightDust/BetterLeavesPack/pull/45#issue-2242476762 

It adds support for the fruit leaves and hoary leaves too!

**Comment by Motschen** [comment]
I just merged the PR, thanks again, Liam!
