### ISSUE TITLE
Good Ending's Cypress Planks are somehow registered as leaves

### ISSUE THREAD

**Issue by Liamgrayskull** [TeamMidnightDust/BetterLeavesPack#44]
![2024-04-14_16 19 57](https://github.com/TeamMidnightDust/BetterLeavesPack/assets/129421895/fea844c9-e498-4224-b885-163a05041e86)
https://www.curseforge.com/minecraft/mc-mods/good-ending

is this a patchable issue? *or one I could directly add/change the texture for to remove

**Comment by Motschen** [comment]
The mod seems to be basing the plank model off of the leaves model, which is just bad on their side.
I could fix this on my side, but it may be better to fix this in the actual mod.
