### ISSUE TITLE
(Mod Support) Ars Nouveau

### ISSUE THREAD

**Issue by MrProton657** [TeamMidnightDust/BetterLeavesPack#46]
I kindly want to ask you to add support for Regions Unexplored mod https://www.curseforge.com/minecraft/mc-mods/regions-unexplored

ars-nouveau would be cool too.
https://www.curseforge.com/minecraft/mc-mods/ars-nouveau

Thank you for your great Resource Pack.

**Comment by Motschen** [comment]
Support for Regions Unexplored is already included in the latest version of the pack.
As for Ars Nouveau, I'll see what I can do in the next update.

**Comment by Motschen** [comment]
Thanks to @Foozey , Ars Nouveau is now also supported, have fun!
