### ISSUE TITLE
Quark ashen leaves missing textures

### ISSUE THREAD

**Issue by polykatt** [TeamMidnightDust/BetterLeavesPack#49]
Ashen leaves from the Quark mod are displaying with the bushy texture when placed but not as an item - which happens for so many other leaves so not too much of an issue. The issue is that it has missing textures when breaking leaves and sometimes even when placed

![2024-07-28_23 36 44](https://github.com/user-attachments/assets/c9140e8c-dd93-4c61-93d6-17142904fc01)
![2024-07-28_23 40 57](https://github.com/user-attachments/assets/d49c5156-9791-491a-ab38-3415b35acd8b)

**Comment by Motschen** [comment]
Fixed by @Foozey in #54 :)
