### ISSUE TITLE
Crashes with no info.

### ISSUE THREAD

**Issue by MagmaBro123** [TeamMidnightDust/BetterLeavesPack#6]
Title says all. Nothing is given upon crash.

**Comment by Motschen** [comment]
Could you please be more specific? What version of minecraft are you using? Are you using any additional mods?

**Comment by MagmaBro123** [comment]
1. 1.16.5.
2. No.

**Comment by Motschen** [comment]
Could you try if it also happens when using other resource packs?

**Comment by MagmaBro123** [comment]
Same thing. Crash, no info.

**Comment by Motschen** [comment]
Well, then it's not caused by this pack. 
I was experiencing similar things back when I was using canvas, might be that.
