### ISSUE TITLE
Broken leaves

### ISSUE THREAD

**Issue by assasin541** [TeamMidnightDust/BetterLeavesPack#7]
Screenshot: https://share.getcloudapp.com/4guOqRzp

**Comment by assasin541** [comment]
Update: it doesn't work with fast graphics on Sodium.

**Comment by Motschen** [comment]
Does it work with fancy graphics?

**Comment by assasin541** [comment]
@Motschen it does.

**Comment by Motschen** [comment]
This pack was made to be used with fancy graphics. Surprisingly it mostly also works on fast graphics, but I wouldn't recommend it, so I'll close this issue now.
